version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data
  backend:
    image: aakabanov/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - static:/static/
      - media:/app/media/
  frontend:
    image: aakabanov/foodgram_frontend
    env_file: .env
    volumes:
      - ../frontend/:/app/result_build/
  nginx:
    image: aakabanov/foodgram_gateway
    env_file: .env
    ports:
      - "8000:80"
    volumes:
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
      - static:/static/
      - media:/app/media/
    depends_on:
      - backend
      - frontend